# +AuthenticationHelpers+ module provides a few helper methods for the app
# authentication, easing the process of getting user-level privileges and
# signing in as a particular user.
#
module AuthenticationHelpers

  # Authenticates an anonymous user (one generated by factory_girl) and runs
  # the steps in the given block as an authenticated user
  #
  def authenticate
    user.confirm!
    visit new_user_session_path

    fill_in 'user_login', with: user.username
    fill_in 'user_password', with: user.password

    click_button 'Sign in'
  end

  private

  def user
    @user ||= create(:user)
  end
end
