development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.db
  pool: 5

test:
  adapter: sqlite3
  encoding: unicode
  database: db/test.db
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: fresk_production
  pool: 5
  username: fresk
  password:
